export type FinancieraDetalleRegistro = {
  plataformaCredito: string;
  creditoAutorizado: number | string | null;
  cuotaInicial: number | string | null;
  tipoPagoInicial: string | null;
  valorCuota: number | string | null;
  numeroCuotas: number | null;
  frecuenciaCuota: string | null;
};

export type RegistroVendedorDetalle = {
  id: number;
  createdAt: string;
  updatedAt: string;
  ciudad: string | null;
  puntoVenta: string | null;
  sedeNombre: string | null;
  clienteNombre: string;
  tipoDocumento: string;
  documentoNumero: string;
  plataformaCredito: string;
  financierasDetalle: FinancieraDetalleRegistro[] | null;
  aceptaDeclaracionIntermediacion: boolean;
  aceptaPoliticaGarantia: boolean;
  aceptaCondicionesCredito: boolean;
  dobleCredito: boolean;
  observacion: string | null;
  referenciaEquipo: string | null;
  almacenamiento: string | null;
  color: string | null;
  serialImei: string | null;
  tipoEquipo: string | null;
  creditoAutorizado: number | null;
  cuotaInicial: number | null;
  valorCuota: number | null;
  numeroCuotas: number | null;
  frecuenciaCuota: string | null;
  correo: string | null;
  whatsapp: string | null;
  fechaNacimiento: string | null;
  fechaExpedicion: string | null;
  direccion: string | null;
  barrio: string | null;
  referenciaFamiliar1Nombre: string | null;
  referenciaFamiliar1Telefono: string | null;
  referenciaFamiliar2Nombre: string | null;
  referenciaFamiliar2Telefono: string | null;
  telefono: string | null;
  simCardRegistro1: string | null;
  simCardRegistro2: string | null;
  medioPago1Tipo: string | null;
  medioPago1Valor: number | null;
  medioPago2Tipo: string | null;
  medioPago2Valor: number | null;
  asesorNombre: string | null;
  jaladorNombre: string | null;
  cerradorNombre: string | null;
  numeroFactura: string | null;
  estadoFacturacion: string | null;
  estadoVentaRegistro: string | null;
  firmaClienteDataUrl: string | null;
  fotoEntregaDataUrl: string | null;
  confirmacionCliente: boolean;
  perfilVendedorNombre: string | null;
  perfilVendedorTipo: string | null;
};
